name: deploy-oliverbleen.net

on:
  push:
    tags:
      - 'v*'

jobs:
  coverage:
    runs-on: ubuntu-lastest
    
    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: SFTP Upload
      - uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{secrets.SFTP_URL}}
          username: ${{secrets.SFTP_USERNAME}}
          password: ${{secrets.SFTP_PASSWORD}}
          port: 21
          uploads: |
            ./README.md => ./wwwroot/README.md
          ignore: |
            *.git
            LICENSE
        
